services:
  app:
    image: django_app
    env_file:
      - .env
    build:
      context: .
      network: host
    volumes:
      - static-volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      app-postgres:
        condition: service_healthy
    networks:
      - backend
  app-postgres:
    image: postgres:15-alpine
    volumes:
      - app-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend
  app-nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - static-volume:/app/static
      depends_on:
        - app
      networks:
        - backend
      restart: always

volumes:
  app-postgres:
    name: app-postgres
  static-volume:
    name: static-volume

networks:
  backend:
    name: backend
    driver: bridge
